# Numpy - Numerical Python

A Python Library used for working with Arrays.It was created in 2005 by Travis Oliphant.In python we also have lists but there are generally slow to process so numpy is almost 50x faster then usuall lists. Numpy is faster then lists because arrays are stored in contiguous location(locality of reference) in numpy unlike lists which makes numpy faster .

# Installing Numpy Using   -   

In [1]:
pip install numpy

In [2]:
#import numpy using np as alias
import numpy as np

In [3]:
#creating my first array
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
#check numpy version 
np.__version__

'1.23.5'

# Numpy Arrays

In [5]:
#array() function is used to create numpy ndarray
arr = np.array([0,4,8,9])
print(arr)
type(arr)

[0 4 8 9]


numpy.ndarray

# Array Dimensions
Dimensions in array are mainly of 3 types - 1d, 2d, 3d etc.

# 0-D Array
0-D arrays are scalors i.e each value in it is a o-d array

In [6]:
arr_0 = np.array(42)
print(arr_0)

42


# 1-D Array



In [7]:
arr_1 = np.array([1,5,6,7])
arr_1

array([1, 5, 6, 7])

# 2-D Arrays

In [8]:
arr_2 = np.array([[1,2,3],[4,5,6]])
arr_2

array([[1, 2, 3],
       [4, 5, 6]])

# 3-D Arrays

In [9]:
arr_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,8,6]]])
arr_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10,  8,  6]]])

In [10]:
#ndim returns dimension that tell us how many dimensions the array have
print(arr_0.ndim)
print(arr_1.ndim)
print(arr_2.ndim)

0
1
2


# Higher Dimensional Arrays

In [11]:
arr_HD = np.array([4,5,6,7], ndmin=5)
print(arr_HD)

[[[[[4 5 6 7]]]]]


# Acessing Array Elements

In [12]:
arr = np.array([1,2,3,4])
print(arr[0])

1


In [13]:
print(arr[0]  + arr[3])

5


In [14]:
arr = np.array([[67,87,34],[23,56,78]])
arr[0,1]

87

In [15]:
arr_3[0,1,2]

6

# Array Slicing
Slicing in python means taking elements from one given index to another given index
[start : end]

In [16]:
arr_1[0:3]

array([1, 5, 6])

In [17]:
arr_1[1:]

array([5, 6, 7])

In [18]:
array_1 = np.array([4,5,6,7,8,9,0])
array_1[-3:-1]

array([8, 9])

# Data Types In Numpy
. i - integer
. b - boolean
. u = unsigned integer
. f - float
. c - complex float
. m - timedelta
. M - datetime
. O - object
. S - string
. U - unicode string 
. V - fixed chunk of memory

In [19]:
arr_1.dtype

dtype('int32')

In [20]:
arr_str = np.array(['apple', 'banana','cherry'])
arr_str.dtype

dtype('<U6')

In [21]:
arr = np.array([1,2,3,4], dtype='S')
arr.dtype

dtype('S1')

In [22]:
newarr = arr.astype('i')

In [23]:
newarr

array([1, 2, 3, 4], dtype=int32)

In [24]:
arr = np.array([3,4,5,6,7])
x = arr.copy()
arr[0] = 56
print(arr)
print(x)

[56  4  5  6  7]
[3 4 5 6 7]


# Numpy array Shape

In [25]:
arr_3.shape

(2, 2, 3)

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Iterating arrays

In [27]:
itr_array = np.array([4,5,2,7,9])
itr_array

array([4, 5, 2, 7, 9])

In [28]:
for p in itr_array :
    print(p)

4
5
2
7
9


In [29]:
itr_arr2 = np.array([[1,2,3],[4,5,6]])
for x in itr_arr2 :
    print(x)

[1 2 3]
[4 5 6]


In [31]:
for x in itr_arr2 :
    for y in x :
        print(y)

1
2
3
4
5
6


In [33]:
for x in np.nditer(itr_arr2) :
    print(x)

1
2
3
4
5
6


# Joining Numpy Arrays
There are three methods which can be used for concatenation .These are Concatenate(), stack(), hstack(), vstack(),dstack() etc.

In [36]:
arr1 = np.array([[4,5],[67,8]])
arr2 = np.array([[45,23],[12,5]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 4  5 45 23]
 [67  8 12  5]]


In [37]:
arr_new = np.stack((arr1,arr2),axis=1)

In [38]:
arr_new

array([[[ 4,  5],
        [45, 23]],

       [[67,  8],
        [12,  5]]])

# Numpy Splitting Array
we pass the array which we want to split and the number of splits we need inside the array_split func

In [40]:
array_split1 = np.array([34,56,78,89,45,12])
newarray = np.array_split(array_split1, 3)
newarray

[array([34, 56]), array([78, 89]), array([45, 12])]

In [41]:
#accessing elements from the splitted array
newarray[0]

array([34, 56])

In [44]:
search_arr = np.array([1,2,3,4,5,6,7])
x = np.where(search_arr==4)
print(x)

(array([3], dtype=int64),)


In [45]:
y = np.searchsorted(search_arr, 4)

In [46]:
y

3

# Sorting Arrays
sorting means putting array into sorted sequence

In [47]:
arr = np.array([3,2,4,5])
np.sort(arr)

array([2, 3, 4, 5])